// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdksmWVXnJzgP-jYvoPs-crUW5rrBT2E',
    appId: '1:812955848930:web:1095f4934103a9bb1fcebb',
    messagingSenderId: '812955848930',
    projectId: 'fir-example-33c88',
    authDomain: 'fir-example-33c88.firebaseapp.com',
    storageBucket: 'fir-example-33c88.firebasestorage.app',
    measurementId: 'G-YZP8XK8111',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGB0WTLmQEFuufR3K8wXdb-nucNWzqKE',
    appId: '1:812955848930:android:1e16c8f482b5e8951fcebb',
    messagingSenderId: '812955848930',
    projectId: 'fir-example-33c88',
    storageBucket: 'fir-example-33c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHpqJj4O6usP3hXIPBvijvA62VxUgFyU',
    appId: '1:812955848930:ios:a576ff8464ef546c1fcebb',
    messagingSenderId: '812955848930',
    projectId: 'fir-example-33c88',
    storageBucket: 'fir-example-33c88.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHpqJj4O6usP3hXIPBvijvA62VxUgFyU',
    appId: '1:812955848930:ios:a576ff8464ef546c1fcebb',
    messagingSenderId: '812955848930',
    projectId: 'fir-example-33c88',
    storageBucket: 'fir-example-33c88.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvdksmWVXnJzgP-jYvoPs-crUW5rrBT2E',
    appId: '1:812955848930:web:4a50171e6c46f3071fcebb',
    messagingSenderId: '812955848930',
    projectId: 'fir-example-33c88',
    authDomain: 'fir-example-33c88.firebaseapp.com',
    storageBucket: 'fir-example-33c88.firebasestorage.app',
    measurementId: 'G-FZ1G75ZKLG',
  );
}
