// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBB2msiRH81K114r-4R4Zc1KLqNTHG3w',
    appId: '1:941896840745:web:4c07183932a60ab638ce38',
    messagingSenderId: '941896840745',
    projectId: 'challange-code',
    authDomain: 'challange-code.firebaseapp.com',
    storageBucket: 'challange-code.firebasestorage.app',
    measurementId: 'G-53S0NBFNX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBamPxidAxUu3xITF2gizHckQ3eYYjGI-4',
    appId: '1:941896840745:android:81e2509279bd521d38ce38',
    messagingSenderId: '941896840745',
    projectId: 'challange-code',
    storageBucket: 'challange-code.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNymih6nR55GKfi_SEFbZwPOiM1a3ifqE',
    appId: '1:941896840745:ios:f5422c14c76f716938ce38',
    messagingSenderId: '941896840745',
    projectId: 'challange-code',
    storageBucket: 'challange-code.firebasestorage.app',
    iosBundleId: 'com.example.demoChallengeCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNymih6nR55GKfi_SEFbZwPOiM1a3ifqE',
    appId: '1:941896840745:ios:f5422c14c76f716938ce38',
    messagingSenderId: '941896840745',
    projectId: 'challange-code',
    storageBucket: 'challange-code.firebasestorage.app',
    iosBundleId: 'com.example.demoChallengeCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBB2msiRH81K114r-4R4Zc1KLqNTHG3w',
    appId: '1:941896840745:web:09caf6c49df5346338ce38',
    messagingSenderId: '941896840745',
    projectId: 'challange-code',
    authDomain: 'challange-code.firebaseapp.com',
    storageBucket: 'challange-code.firebasestorage.app',
    measurementId: 'G-JDBTMHMC3X',
  );
}
